

future: true
email: antae0714@gmail.com
PoneNumber: 010-2714-0591
github_username: antae714
Projects:
 - "UnrealProject"

include:
 - assets
 
 
markdown: kramdown
kramdown:
  input: GFM           # GitHub Flavored Markdown 사용
  syntax_highlighter: null   # 서버측 하이라이팅 끄기